"""
convert_paper_v4.py  —  ALICE paper → Word .docx
Figures are embedded INLINE at every *(Figure N — ... — appears below)* marker.
The Figure Index section at the end is kept as a reference list (no images there).
"""

import re
from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ── paths ──────────────────────────────────────────────────────────────────────
BASE        = Path("/home/user/webapp")
PAPER_MD    = BASE / "alice_paper.md"
FIGURES_DIR = BASE / "paper_figures"
OUTPUT_DOCX = BASE / "ALICE_Q1_Paper_Eliasaf_2026.docx"

# ── figure registry: key → (filename, caption) ────────────────────────────────
FIGURE_INFO = {
    1:  ("fig_A_rup_nps_timeseries.png",
         "Figure 1: Weekly RUP and NPS Trends — Weeks 18 through 24. "
         "RUP (left axis, blue) rises from baseline 5.41% to 7.89% at Week 24. "
         "NPS (right axis, orange) shows the GPS-failure trough at Week 22 "
         "preceding the RUP plateau — consistent with the 2-week lag structure."),
    2:  ("fig_B_correlation.png",
         "Figure 2: NPS–RUP Lagged Correlation Scatter Plot (r = 0.638, p = 0.03). "
         "NPS at week t plotted against RUP at week t+2. The fitted regression "
         "line confirms a positive predictive relationship; the Week 22 crisis "
         "point is visible as the bottom-left outlier."),
    3:  ("fig_C_digital_twin.png",
         "Figure 3: Digital Twin P20/P50/P80 RUP Trajectory Scenarios through Q4 2026. "
         "P50 (realistic scenario) reaches the 30% municipal target; P80 (optimistic) "
         "projects 38% with Route C activation. Observed Weeks 18–24 plotted as solid circles."),
    4:  ("fig_D_architecture.png",
         "Figure 4: ALICE Four-Layer Architecture with MCP-RAG Pipeline. "
         "Bottom-to-top: Physical Reality Layer → Data Integration Layer → "
         "Model & Knowledge Layer (ChromaDB RAG) → Decision & Action Layer (Claude API / MCP). "
         "Arrows denote data flows; the self-calibration feedback loop is shown in red."),
    5:  ("fig_E_pdca_loop.png",
         "Figure 5: ALICE Self-Calibrating PDCA Loop. Weekly operational cycle (Plan–Do–Check–Act) "
         "at the inner ring; monthly trajectory recalibration at the middle ring; "
         "quarterly strategic review at the outer ring. Claude API drives the Check stage "
         "at all three timescales."),
    6:  ("fig_F_nps_bands.png",
         "Figure 6: NPS Classification Bands and Weekly Results (Weeks 18–24). "
         "Background bands: Critical (1.0–2.4, red), Developing (2.5–3.4, yellow), "
         "Good (3.5–3.9, green), Excellent (≥4.0, blue). "
         "Week 22 falls in Critical band, triggering automated alert and task generation."),
    7:  ("fig2_dashboard.png",
         "Figure 7: ALICE Management Dashboard. KPI tiles display real-time RUP, NPS, "
         "alert status, and active tasks. Chart area shows the NPS/RUP time series "
         "and Digital Twin trajectory. Bootstrap 5 RTL layout for Hebrew-language users."),
    8:  ("fig4_analysis_parents.png",
         "Figure 8: Parent WhatsApp Analysis Interface. Left panel shows analysis input "
         "and controls; right panel renders the Claude API structured JSON output "
         "including NPS score, sentiment breakdown, key themes, and supporting WhatsApp quotes."),
    9:  ("fig5_analysis_students.png",
         "Figure 9: Student WhatsApp Analysis Interface. Parallel NLP pipeline for "
         "student group messages, producing a separate NPS score for the student stakeholder group. "
         "Enables comparison of parent and student satisfaction dynamics."),
    10: ("fig6_comparison.png",
         "Figure 10: Parent vs. Student NPS Comparison View. Side-by-side Chart.js bar chart "
         "overlaying parent NPS (blue) and student NPS (orange) for each analysis week. "
         "Divergence between stakeholder groups flags issues affecting specific demographics."),
    11: ("fig3_students.png",
         "Figure 11: Student Management with WhatsApp Integration. Data table displays "
         "student records with the WhatsApp phone field enabling targeted outreach to "
         "the 101 unaffiliated eligible students — a direct RUP growth lever."),
    12: ("fig7_tasks.png",
         "Figure 12: Automated Task Management Interface. Tasks generated by the "
         "Claude API analysis pipeline, with priority classification, stakeholder assignment, "
         "category, and deadline. Human-in-the-Loop flags distinguish AI-generated from "
         "human-confirmed tasks."),
    13: ("fig8_weekly.png",
         "Figure 13: Weekly Report Interface. Structured HTML report rendered by the "
         "Node.js report generation module and distributed to all stakeholder groups "
         "within two hours of the Sunday WhatsApp export collection."),
    14: ("fig9_optimization.png",
         "Figure 14: Route Optimization with Geospatial Mapping. Leaflet.js interactive map "
         "showing Route A and Route B coverage areas, student density overlay by school, "
         "and proposed Route C expansion zone for the P80 scenario."),
}

# ── detect figure numbers from inline marker lines ────────────────────────────
# Matches: *(Figure 4 — ... — appears below)* or *(Figure 9 ... | Figure 10 ... — appear below)*
MARKER_RE = re.compile(r'^\*\(Figure[s]?\s+([\d ,|]+)', re.IGNORECASE)
FIG_NUM_RE = re.compile(r'\b(\d+)\b')


def extract_fig_numbers(marker_line: str):
    """Return list of integer figure numbers from a marker line."""
    nums = FIG_NUM_RE.findall(marker_line)
    return [int(n) for n in nums if int(n) in FIGURE_INFO]


# ── helpers ──────────────────────────────────────────────────────────────────
def set_style(doc):
    """Apply clean academic styling."""
    # Body text
    normal = doc.styles['Normal']
    normal.font.name = 'Times New Roman'
    normal.font.size = Pt(12)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = Pt(18)

    # Headings
    for lvl, sz in [(1, 16), (2, 14), (3, 12)]:
        h = doc.styles[f'Heading {lvl}']
        h.font.name = 'Times New Roman'
        h.font.size = Pt(sz)
        h.font.bold = True
        h.font.color.rgb = RGBColor(0x00, 0x00, 0x00)
        h.paragraph_format.space_before = Pt(12)
        h.paragraph_format.space_after  = Pt(6)

    # Caption style (create if absent)
    if 'Caption' not in [s.name for s in doc.styles]:
        cap = doc.styles.add_style('Caption', WD_STYLE_TYPE.PARAGRAPH)
    else:
        cap = doc.styles['Caption']
    cap.font.name  = 'Times New Roman'
    cap.font.size  = Pt(10)
    cap.font.italic = True
    cap.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
    cap.paragraph_format.alignment   = WD_ALIGN_PARAGRAPH.CENTER
    cap.paragraph_format.space_before = Pt(4)
    cap.paragraph_format.space_after  = Pt(10)


def insert_figure(doc, fig_num: int, width_inches=5.8):
    """Insert figure image + caption paragraph into doc."""
    info = FIGURE_INFO.get(fig_num)
    if not info:
        return
    fname, caption = info
    fpath = FIGURES_DIR / fname
    if not fpath.exists():
        print(f"  ⚠️  Missing figure file: {fpath}")
        return

    # separator line before figure
    sep = doc.add_paragraph()
    sep.paragraph_format.space_before = Pt(6)
    sep.paragraph_format.space_after  = Pt(2)

    # image paragraph
    img_para = doc.add_paragraph()
    img_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    img_para.paragraph_format.space_before = Pt(4)
    img_para.paragraph_format.space_after  = Pt(2)
    run = img_para.add_run()
    run.add_picture(str(fpath), width=Inches(width_inches))

    # caption paragraph
    cap_para = doc.add_paragraph(style='Caption')
    cap_para.text = caption
    cap_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    print(f"  ✓ Figure {fig_num}: {fname}")


def apply_inline_formatting(para, text: str):
    """Add a run with basic **bold** and *italic* markdown rendering."""
    # Split by **bold** and *italic*
    pattern = re.compile(r'\*\*(.+?)\*\*|\*(.+?)\*|(`[^`]+`)')
    pos = 0
    for m in pattern.finditer(text):
        # plain text before match
        if m.start() > pos:
            para.add_run(text[pos:m.start()])
        if m.group(1):       # **bold**
            run = para.add_run(m.group(1))
            run.bold = True
        elif m.group(2):     # *italic*
            run = para.add_run(m.group(2))
            run.italic = True
        elif m.group(3):     # `code`
            run = para.add_run(m.group(3)[1:-1])
            run.font.name = 'Courier New'
        pos = m.end()
    if pos < len(text):
        para.add_run(text[pos:])


# ── main converter ─────────────────────────────────────────────────────────────
def convert():
    doc = Document()
    set_style(doc)

    lines = PAPER_MD.read_text(encoding='utf-8').splitlines()

    # State flags
    in_figure_index = False    # suppress image insertion in Figure Index section
    in_references   = False
    pending_figures = []       # figures queued for insertion after next real paragraph

    def flush_pending():
        for fn in pending_figures:
            insert_figure(doc, fn)
        pending_figures.clear()

    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.strip()
        i += 1

        # ── horizontal rule ─────────────────────────────────────────────────
        if line in ('---', '***', '___'):
            flush_pending()
            p = doc.add_paragraph()
            pPr = p._p.get_or_add_pPr()
            pBdr = OxmlElement('w:pBdr')
            bottom = OxmlElement('w:bottom')
            bottom.set(qn('w:val'), 'single')
            bottom.set(qn('w:sz'), '4')
            bottom.set(qn('w:space'), '1')
            bottom.set(qn('w:color'), 'AAAAAA')
            pBdr.append(bottom)
            pPr.append(pBdr)
            p.paragraph_format.space_after = Pt(6)
            continue

        # ── headings ────────────────────────────────────────────────────────
        if line.startswith('# ') and not line.startswith('## '):
            flush_pending()
            p = doc.add_heading(line[2:].strip(), level=1)
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            continue

        if line.startswith('## '):
            flush_pending()
            heading_text = line[3:].strip()
            if heading_text == 'Figure Index':
                in_figure_index = True
            elif heading_text == 'References':
                in_figure_index = False
                in_references = True
            else:
                in_figure_index = False
                in_references = False
            doc.add_heading(heading_text, level=2)
            continue

        if line.startswith('### '):
            flush_pending()
            doc.add_heading(line[4:].strip(), level=3)
            continue

        # ── blank line ───────────────────────────────────────────────────────
        if not line:
            continue

        # ── inline figure marker lines ────────────────────────────────────────
        # Pattern: *(Figure N — ... — appears below)* or *(Figure N ... | Figure M ...)*
        if line.startswith('*(Figure') and ('appears below' in line or 'appear below' in line):
            fig_nums = extract_fig_numbers(line)
            if fig_nums:
                pending_figures.extend(fig_nums)
            # Don't output the marker as text — just queue the figures
            continue

        # ── Figure Index bullets — keep as text, no images ─────────────────
        if in_figure_index and line.startswith('- **Figure'):
            # Render as a plain reference list item (text only)
            p = doc.add_paragraph(style='Normal')
            p.paragraph_format.left_indent = Pt(18)
            p.paragraph_format.space_after  = Pt(3)
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', line.lstrip('- '))
            p.add_run(clean)
            continue

        # ── metadata header lines (bold: value) ──────────────────────────────
        if line.startswith('**') and ':' in line and line.endswith('**') is False:
            # e.g. **Author:** Levi Eliasaf
            flush_pending()
            p = doc.add_paragraph(style='Normal')
            p.paragraph_format.space_after = Pt(2)
            apply_inline_formatting(p, line)
            continue

        # ── regular paragraph ─────────────────────────────────────────────────
        flush_pending()

        p = doc.add_paragraph(style='Normal')

        # First-line indent for body paragraphs (not after headings handled by style)
        if not in_figure_index and not in_references:
            p.paragraph_format.first_line_indent = Pt(18)

        apply_inline_formatting(p, line)

    # Flush any remaining pending figures at end of document
    flush_pending()

    doc.save(str(OUTPUT_DOCX))
    size_mb = OUTPUT_DOCX.stat().st_size / (1024 * 1024)
    print(f"\n✅  Saved: {OUTPUT_DOCX}")
    print(f"   Size : {size_mb:.2f} MB")


if __name__ == '__main__':
    convert()
